### ISSUE TITLE
Does not work on samsung?

### ISSUE THREAD

**Issue by rpbaltazar** [ionicthemes/ionic2-google-login#1]
I have tried to deploy the app in a Samsung tablet (SM-T231 if it matters) running android 4.4.2.

when i try to press login, the following error comes up in the logcat:

```
I/GooglePlugin(16037): Building Google options
I/GooglePlugin(16037): Building GoogleApiClient
I/GooglePlugin(16037): GoogleApiClient built
I/GooglePlugin(16037): Trying to Log in!
E/Parcel  ( 1181): Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
E/Parcel  ( 1181): java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
E/Parcel  ( 1181): 	at java.lang.Class.classForName(Native Method)
E/Parcel  ( 1181): 	at java.lang.Class.forName(Class.java:251)
E/Parcel  ( 1181): 	at java.lang.Class.forName(Class.java:216)
E/Parcel  ( 1181): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2140)
E/Parcel  ( 1181): 	at android.os.Parcel.readParcelable(Parcel.java:2104)
E/Parcel  ( 1181): 	at android.os.Parcel.readValue(Parcel.java:2020)
E/Parcel  ( 1181): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
E/Parcel  ( 1181): 	at android.os.Bundle.unparcel(Bundle.java:249)
E/Parcel  ( 1181): 	at android.os.Bundle.getString(Bundle.java:1118)
E/Parcel  ( 1181): 	at android.content.Intent.getStringExtra(Intent.java:5145)
E/Parcel  ( 1181): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1466)
E/Parcel  ( 1181): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1061)
E/Parcel  ( 1181): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4067)
E/Parcel  ( 1181): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:3965)
E/Parcel  ( 1181): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:159)
E/Parcel  ( 1181): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2646)
E/Parcel  ( 1181): 	at android.os.Binder.execTransact(Binder.java:404)
E/Parcel  ( 1181): 	at dalvik.system.NativeStart.run(Native Method)
E/Parcel  ( 1181): Caused by: java.lang.NoClassDefFoundError: com/google/android/gms/auth/api/signin/internal/SignInConfiguration
E/Parcel  ( 1181): 	... 18 more
E/Parcel  ( 1181): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.signin.internal.SignInConfiguration" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/Parcel  ( 1181): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Parcel  ( 1181): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/Parcel  ( 1181): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/Parcel  ( 1181): 	... 18 more
```

**Comment by rpbaltazar** [comment]
Ok, can't really explain what happened but things are working now.
Things i've done to try to solve the problem:

1) Set a minimum version of Sdk and target Sdk for android
2) Added an account and open google play store
3) Removed and added again the android platform with cordova platform add/remove
